l_japanese:
#穀物農場
pmg_farming_rice: "生産"
pmg_secondary_rice: "日本酒"
pmg_mechanization_farms: "機械化"
pmg_farming_mayze: "生産"
pmg_secondary_mayze: "スイートコーン"
pmg_mechanization_farms: "機械化"
pmg_farming_wheat: "一次生産"
pmg_secondary_wheat: "うどん"
pmg_mechanization_farms: "機械化"

#牧畜
pmg_farming_cow: "生産"
pmg_luxury_beef: "高級肉"
pmg_management_livestock: "家畜管理"
pmg_refrigeration: "冷蔵"
pmg_farming_pig: "生産"
pmg_management_livestock: "家畜管理"
pmg_refrigeration: "冷蔵"
pmg_farming_chicken: "生産"
pmg_feather: "羽毛"
pmg_management_livestock: "家畜管理"
pmg_refrigeration: "冷蔵"
pmg_farming_dairy: "生産"
pmg_meat: "食肉"
pmg_management_livestock: "家畜管理"
pmg_refrigeration: "冷蔵"

#商品農園
pmg_base_coffee: "生産"
pmg_train: "輸送"
pmg_base_cotton: "生産"
pmg_train: "輸送"
pmg_base_tea: "生産"
pmg_train: "輸送"
pmg_base_tobacco: "生産"
pmg_train: "輸送"
pmg_base_sugar: "生産"
pmg_train: "輸送"
pmg_base_orchard: "生産"
pmg_train: "輸送"
pmg_base_vegetable: "生産"
pmg_train: "輸送"
pmg_base_fishery: "生産"
pmg_deep_sea_fishery: "遠洋漁業"
pmg_refrigeration: "冷蔵"
pmg_base_culture_farm: "生産"
pmg_refrigeration: "冷蔵"
pmg_base_fishery: "生産"
pmg_deep_sea_fishery: "高級養殖"
pmg_refrigeration: "冷蔵"
pmg_reserved_forest: "生産"
pmg_softwood: "生産"
pmg_train: "輸送"
pmg_hardwood: "生産"
pmg_train: "輸送"
pmg_base_coal: "採掘道具"
pmg_explosive_coal: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_asbestos: "採掘道具"
pmg_explosive_asbestos: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_iron: "採掘道具"
pmg_explosive_iron: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_sulfer: "採掘道具"
pmg_explosive_sulfer: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_minor_metals: "採掘道具"
pmg_explosive_minor_metals: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_lead: "採掘道具"
pmg_explosive_lead: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_gold: "採掘道具"
pmg_explosive_gold: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_base_silver: "採掘道具"
pmg_explosive_silver: "爆薬"
pmg_drainage: "排水"
pmg_train: "運送"
pmg_mining_ocean: "鉱石採掘"
pmg_extraction_ocean: "石油抽出"
pmg_train: "運送"