l_japanese:
#農業
pmg_farming_rice: "生産"
pmg_secondary_rice: "日本酒"
pmg_mechanization_farms: "機械化"
pmg_farming_mayze: "生産"
pmg_secondary_mayze: "スイートコーン"
pmg_mechanization_farms: "機械化"
pmg_farming_wheat: "一次生産"
pmg_secondary_wheat: "うどん"
pmg_mechanization_farms: "機械化"
pmg_cattle_ranch: "牛牧場"
pmg_refrigeration: "冷蔵"
pmg_pig_ranch: "養豚"
pmg_chicken_ranch: "養鶏"
pmg_vineyard: "ワイン栽培"
pmg_whiskey: "ウィスキー醸造"
pmg_cotton: "綿花生産"
pmg_tea: "茶葉生産"
pmg_tobacco: "タバコ生産"
pmg_sugarcane: "サトウキビ生産"
pmg_transport: "輸送"
pmg_orchard: "果樹園"
pmg_vegetable_farm: "野菜生産"

#漁業
pmg_fishery: "漁業"
pmg_ocean_fishing: "海洋漁業"
pmg_aquaculture: "養殖"
pmg_land_aquaculture: "陸上養殖"

#林業
pmg_hardwood: "硬材"
pmg_charcoal: "木炭"
pmg_softwood: "軟材"
pmg_carbonized_wood: "炭化木"

#鉱業 - 鉱山
pmg_drilling_coal: "石炭採掘"
pmg_explosive_coal: "火薬使用"
pmg_automation: "自動化"
pmg_byproducts: "副産物"
pmg_drilling_iron: "鉄鉱石採掘"
pmg_explosive_iron: "火薬使用"
pmg_drilling_lead: "鉛鉱石採掘"
pmg_explosive_lead: "火薬使用"
pmg_drilling_sulfur: "硫黄採掘"
pmg_explosive_sulfur: "火薬使用"
pmg_drilling_gold: "金鉱石採掘"
pmg_explosive_gold: "火薬使用"
pmg_drilling_minor_metals: "レアメタル採掘"
pmg_explosive_minor_metals: "火薬使用"
pmg_drilling_asbestos: "アスベスト採掘"
pmg_base_building_gold_fields: "採金"

#鉱業 - 資源抽出
pmg_drilling_oil: "原油採掘"
pmg_import_oil: "原油輸入"
pmg_processing_oil: "原油精製"
pmg_drilling_gas: "天然ガス採掘"
pmg_import_gas: "天然ガス輸入"
pmg_uranium_enrichment: "ウラン濃縮"

#工業 - 食品
pmg_wheat_importing: "小麦輸入"
pmg_bread: "パン"
pmg_manufacturing_management_bread: "パン製造"
pmg_fish_canned: "魚缶詰"
pmg_meat_canned: "肉缶詰"
pmg_vegetable_canned: "野菜缶詰"
pmg_manufacturing_management_canned: "缶詰製造"
pmg_juice: "ジュース"
pmg_caffeine_drink: "カフェイン飲料"
pmg_beer: "ビール"
pmg_manufacturing_management_juice: "ジュース製造"
pmg_sweets: "菓子"
pmg_manufacturing_management_sweets: "菓子製造"
pmg_vegetable: "野菜"

#工業 - 軽工業
pmg_glass: "ガラス生産"
pmg_manufacturing_management_glass: "製造管理"
pmg_computer: "コンピュータ"
pmg_manufacturing_management_computer: "製造管理"
pmg_communication_device: "通信機器"
pmg_manufacturing_management_communication_device: "製造管理"
pmg_furniture: "家具生産"
pmg_manufacturing_management_furniture: "製造管理"
pmg_order_furniture: "注文家具生産"
pmg_manufacturing_management_order_furniture: "製造管理"
pmg_musical_instruments: "楽器生産"
pmg_manufacturing_management_musical_instruments: "製造管理"
pmg_chemical_fiber: "化学繊維"
pmg_manufacturing_management_chemical_fiber: "製造管理"
pmg_clothes: "衣類生産"
pmg_manufacturing_management_clothes: "製造管理"
pmg_order_clothes: "注文衣類生産"
pmg_manufacturing_management_order_clothes: "製造管理"
pmg_ceramics: "セラミック生産"
pmg_manufacturing_management_ceramics: "製造管理"
pmg_machine_tools: "工作機械生産"
pmg_manufacturing_management_machine_tools: "製造管理"
pmg_paper: "紙生産"
pmg_manufacturing_management_paper: "製造管理"
pmg_game_consoles: "ゲーム機生産"
pmg_manufacturing_management_game_console: "製造管理"
pmg_television: "テレビ生産"
pmg_manufacturing_management_television: "製造管理"
pmg_washing_machine: "洗濯機生産"
pmg_manufacturing_management_washing_machine: "製造管理"
pmg_refrigerator: "冷蔵庫生産"
pmg_manufacturing_management_refrigerator: "製造管理"
pmg_camera: "カメラ生産"
pmg_manufacturing_management_camera: "製造管理"

#工業 - 重工業
pmg_chemical_fertilizer: "化学肥料生産"
pmg_metal_processing: "金属加工"
pmg_conberting: "転炉"
pmg_aircraft: "航空機生産"
pmg_drone: "ドローン生産"
pmg_manufacturing_management_drone: "製造管理"
pmg_synthetic_resin: "合成樹脂生産"
pmg_automobile: "自動車生産"
pmg_manufacturing_management_automobile: "製造管理"
pmg_luxury_automobile: "高級車生産"
pmg_manufacturing_management_luxury_automobile: "製造管理"
pmg_medicines: "医薬品生産"
pmg_large_shipbuilding: "大型船舶建造"
pmg_synthetic_dye: "合成染料生産"
pmg_engine: "エンジン生産"
pmg_manufacturing_management_engine: "製造管理"
pmg_robot: "ロボット生産"
pmg_manufacturing_management_robot: "製造管理"
pmg_explosive: "火薬生産"
pmg_housing_construction: "住宅建設"
pmg_insulation_material: "断熱材生産"

#サービス - 民間
pmg_shopping_street: "商店街"
pmg_financial_service: "金融サービス"
pmg_exparts_affairs: "専門サービス"
pmg_travel_service: "旅行サービス"
pmg_digital_service: "デジタルサービス"
pmg_printing: "印刷"
pmg_broadcasting: "放送"
pmg_special_service_media_industry: "メディア業界"
pmg_publishing: "出版"
pmg_special_service_publishing_industry: "出版業界"
pmg_small_vehicle: "小型車"
pmg_large_vehicle: "大型車"
pmg_travel_service: "旅行サービス"
pmg_special_service_travel_industry: "旅行業界"
pmg_digitalization: "デジタル化"
pmg_medical_service: "医療サービス"

#サービス - 行政
pmg_administration: "行政"
pmg_university_of_art: "芸術大学"
pmg_university: "大学"
pmg_art_museum: "美術館"
pmg_base_building_construction_sector: "建設業"